"""004 — Add dbwd_rates table and indexes for time-series analytics queries.

Revision ID: 004
Revises: 003
Create Date: 2026-04-25 00:03:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add index for decision volume by day
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_decisions_date_verdict 
        ON decisions(DATE_TRUNC('day', created_at), verdict)
    """)
    
    # Create dbwd_rates table
    op.create_table(
        'dbwd_rates',
        sa.Column('id', UUID(), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('trade', sa.Text(), nullable=False),
        sa.Column('locality', sa.Text(), nullable=False),
        sa.Column('rate', sa.Float(), nullable=False),
        sa.Column('fringe', sa.Float(), nullable=False, server_default='0'),
        sa.Column('effective_date', sa.Date(), nullable=False),
        sa.Column('wage_determination_number', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
    )
    
    # Create unique constraint for trade + locality + effective_date
    op.create_unique_constraint(
        'uq_dbwd_rates_trade_locality_date',
        'dbwd_rates',
        ['trade', 'locality', 'effective_date']
    )
    
    op.create_index('idx_dbwd_trade_locality', 'dbwd_rates', ['trade', 'locality'])
    op.create_index('idx_dbwd_effective_date', 'dbwd_rates', ['effective_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dbwd_effective_date', table_name='dbwd_rates')
    op.drop_index('idx_dbwd_trade_locality', table_name='dbwd_rates')
    op.drop_constraint('uq_dbwd_rates_trade_locality_date', 'dbwd_rates', type_='unique')
    op.drop_table('dbwd_rates')
    op.execute("DROP INDEX IF EXISTS idx_decisions_date_verdict")
    # ### end Alembic commands ###


# Legacy SQL for reference
UPGRADE_SQL = """
-- Decision volume by day
CREATE INDEX IF NOT EXISTS idx_decisions_date_verdict
    ON decisions(DATE_TRUNC('day', created_at), verdict);

-- Violation rate by trade
CREATE TABLE IF NOT EXISTS dbwd_rates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trade TEXT NOT NULL,
    locality TEXT NOT NULL,
    rate FLOAT NOT NULL,
    fringe FLOAT NOT NULL DEFAULT 0,
    effective_date DATE NOT NULL,
    wage_determination_number TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(trade, locality, effective_date)
);

CREATE INDEX IF NOT EXISTS idx_dbwd_trade_locality ON dbwd_rates(trade, locality);
CREATE INDEX IF NOT EXISTS idx_dbwd_effective_date ON dbwd_rates(effective_date DESC);
"""

DOWNGRADE_SQL = """
DROP TABLE IF EXISTS dbwd_rates;
DROP INDEX IF EXISTS idx_decisions_date_verdict;
"""
