"""001 — Create audit tables: decisions, audit_events.

Revision ID: 001
Revises: 
Create Date: 2026-04-25 00:00:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB, ARRAY

# revision identifiers
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure pgcrypto extension exists for gen_random_uuid()
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'decisions',
        sa.Column('id', UUID(), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', sa.Text(), nullable=False, unique=True),
        sa.Column('verdict', sa.Text(), nullable=False),
        sa.Column('trust_score', sa.Float(), nullable=False),
        sa.Column('trust_band', sa.Text(), nullable=False),
        sa.Column('requires_human_review', sa.Boolean(), nullable=False, server_default='FALSE'),
        sa.Column('violation_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('warning_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('reasoning_summary', sa.Text(), nullable=True),
        sa.Column('citations', JSONB(), nullable=True, server_default='[]'),
        sa.Column('cost_usd', sa.Float(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('phoenix_trace_id', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
    )
    
    op.create_index('idx_decisions_job_id', 'decisions', ['job_id'])
    op.create_index('idx_decisions_created_at', 'decisions', ['created_at'], unique=False)
    
    op.create_table(
        'audit_events',
        sa.Column('id', UUID(), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_id', sa.Text(), nullable=False),
        sa.Column('event_type', sa.Text(), nullable=False),
        sa.Column('actor', sa.Text(), nullable=False, server_default='system'),
        sa.Column('payload', JSONB(), nullable=True, server_default='{}'),
        sa.Column('regulation_references', ARRAY(sa.Text()), nullable=True, server_default='{}'),
        sa.Column('trace_id', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
    )
    
    op.create_index('idx_audit_events_job_id', 'audit_events', ['job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_events_job_id', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('idx_decisions_created_at', table_name='decisions')
    op.drop_index('idx_decisions_job_id', table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###


# Legacy SQL strings for reference
UPGRADE_SQL = """
CREATE TABLE IF NOT EXISTS decisions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id TEXT NOT NULL UNIQUE,
    verdict TEXT NOT NULL,
    trust_score FLOAT NOT NULL,
    trust_band TEXT NOT NULL,
    requires_human_review BOOLEAN NOT NULL DEFAULT FALSE,
    violation_count INTEGER NOT NULL DEFAULT 0,
    warning_count INTEGER NOT NULL DEFAULT 0,
    reasoning_summary TEXT,
    citations JSONB DEFAULT '[]',
    cost_usd FLOAT,
    latency_ms INTEGER,
    phoenix_trace_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    actor TEXT NOT NULL DEFAULT 'system',
    payload JSONB DEFAULT '{}',
    regulation_references TEXT[] DEFAULT '{}',
    trace_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_decisions_job_id ON decisions(job_id);
CREATE INDEX IF NOT EXISTS idx_decisions_created_at ON decisions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_job_id ON audit_events(job_id);
"""

DOWNGRADE_SQL = """
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS decisions;
"""
