"""002 — Add pgvector extension and regulation_chunks table.

Revision ID: 002
Revises: 001
Create Date: 2026-04-25 00:01:00.000000
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    op.create_table(
        'regulation_chunks',
        sa.Column('id', UUID(), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('chunk_id', sa.Text(), nullable=False, unique=True),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('trade', sa.Text(), nullable=True),
        sa.Column('locality', sa.Text(), nullable=True),
        sa.Column('regulation_cite', sa.Text(), nullable=True),
        sa.Column('wage_determination_number', sa.Text(), nullable=True),
        sa.Column('embedding', sa.Text(), nullable=True),  # Converted to vector(384) below.
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
    )
    op.execute("ALTER TABLE regulation_chunks ALTER COLUMN embedding TYPE vector(384) USING embedding::vector")
    
    op.create_index('idx_chunks_trade_locality', 'regulation_chunks', ['trade', 'locality'])
    
    # Create vector index using raw SQL for ivfflat
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_chunks_embedding 
        ON regulation_chunks 
        USING ivfflat (embedding vector_cosine_ops) 
        WITH (lists = 100)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_embedding', table_name='regulation_chunks')
    op.drop_index('idx_chunks_trade_locality', table_name='regulation_chunks')
    op.drop_table('regulation_chunks')
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###


# Legacy SQL for reference
UPGRADE_SQL = """
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS regulation_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    chunk_id TEXT NOT NULL UNIQUE,
    text TEXT NOT NULL,
    trade TEXT,
    locality TEXT,
    regulation_cite TEXT,
    wage_determination_number TEXT,
    embedding vector(384),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chunks_trade_locality ON regulation_chunks(trade, locality);
CREATE INDEX IF NOT EXISTS idx_chunks_embedding ON regulation_chunks
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
"""

DOWNGRADE_SQL = """
DROP TABLE IF EXISTS regulation_chunks;
DROP EXTENSION IF EXISTS vector;
"""
