"""006 — Add composite index for trust_band and created_at to decisions table.

Revision ID: 006
Revises: 005
Create Date: 2026-05-01 00:00:00.000000
"""

from alembic import op


# revision identifiers
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_decisions_trust_band_date
        ON decisions(trust_band, created_at DESC)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_decisions_trust_band_date")
    # ### end Alembic commands ###

# Legacy SQL for reference
UPGRADE_SQL = """
CREATE INDEX IF NOT EXISTS idx_decisions_trust_band_date
    ON decisions(trust_band, created_at DESC);
"""

DOWNGRADE_SQL = """
DROP INDEX IF EXISTS idx_decisions_trust_band_date;
"""
